set -g mouse on
set -g allow-rename off
set -g automatic-rename off
set -g base-index 1
set -g status-interval 5
set -g status-right-length 100
set -g status-right '#(~/.tmux-status-metrics.sh) | #H | %Y-%m-%d %H:%M'
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind | split-window -h
bind - split-window -v
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
